content_style:
  "body {font-family: "ProximaNova","Helvetica Neue",helvetica,arial,sans-serif}"
menubar: false
toolbar:
  styleselect |
  bold italic forecolor backcolor |
  bullist numlist outdent indent blockquote  |
  table | image link hr insertdatetime |
  fullscreen
statusbar: false
plugins:
  - image
  - link
  - fullscreen
  - table
  - insertdatetime
  - hr
  - textcolor